### ISSUE TITLE
Problem with image printing

### ISSUE THREAD

**Issue by andreadragotta** [SimonWaldherr/zplgfa#8]
Hi, 

I'm try to use this library with a ZD421 but i have some problem because not print any image. 

There are any incompatibily with this printer?

**Comment by SimonWaldherr** [comment]
Most of my tests are with the ZM- and ZT-Series, but it should also work on the ZD-printers.
Does your ZPL work on the Labelary-Viewer: https://labelary.com/viewer.html ?
Can you post the ZPL here?

**Comment by andreadragotta** [comment]
After some test i've identified the problem. 

The problem is the PDF file used for the print (after conversion in image).

Thank you for the support and for the website shared.
