### ISSUE TITLE
Invalid  URL 

### ISSUE THREAD

**Issue by xihajuan2010** [SimonWaldherr/zplgfa#9]
Hi there, 

It looks the url is no longer with a valid cert(simonwaldherr.de), will you update the cert or we just move the package URL to Github?

![image](https://github.com/user-attachments/assets/004a00c6-16a8-469c-8afb-ab2f59ac8e0f)

` go get simonwaldherr.de/go/zplgfa 
go: unrecognized import path "simonwaldherr.de/go/zplgfa": https fetch: Get "https://simonwaldherr.de/go/zplgfa?go-get=1": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: “simonwaldherr.de” certificate is expired
`

Thanks
Alex

**Comment by SimonWaldherr** [comment]
thanks for informing me, I refreshed it, should now work again.
